### ISSUE TITLE
Unexpected Error nach dem einrichten

### ISSUE THREAD

**Issue by r-ober-t** [r00tat/hassio_blaulichtsms#38]
## System Information

version | core-2024.5.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | armv7l
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4982
Installed Version | 1.34.0
Stage | running
Available Repositories | 1468
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.8 GB
disk_used | 9.5 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.13.0), CEC Scanner (3.0), Duck DNS (1.17.0), Let's Encrypt (5.0.18), Google Assistant SDK (2.5.0), MariaDB (2.7.1), Mosquitto broker (6.4.0), Govee to MQTT Bridge (2024.04.29-30cf7732)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 5. Mai 2024 um 19:31
-- | --
current_recorder_run | 6. Mai 2024 um 09:22
estimated_db_size | 895.19 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Die Integration wird nach der Installation und Konfiguration mit einem Eintrag „BlaulichtSMS Kundennummer“ angezeigt, jedoch ohne Geräte oder Entitäten. Es gibt keine weiteren Möglichkeiten, und im Log wird eine Exception angezeigt.

### Reproduction steps

1. Installieren und einrichten (Kundennummer, Benutzername, Passwort)
2. Home Assistant neustarten 
3. Integration bei den Integrationen sichtbar, jedoch ohne Funktion

### Debug logs

```text
*** Error while setting up blaulichtsms platform for binary_sensor *** 

Logger: homeassistant.components.binary_sensor
Quelle: helpers/entity_platform.py:356
Integration: Binärsensor (Dokumentation, Probleme)
Erstmals aufgetreten: 09:22:21 (1 Vorkommnisse)
Zuletzt protokolliert: 09:22:21

Error while setting up blaulichtsms platform for binary_sensor

*** Error while setting up blaulichtsms platform for sensor ***

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:356
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 09:22:21 (1 Vorkommnisse)
Zuletzt protokolliert: 09:22:21

Error while setting up blaulichtsms platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/coordinator.py", line 69, in _async_update_data
    return await self.api.get_last_alarm()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 97, in get_last_alarm
    alarms = await self.get_alarms()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 78, in get_alarms
    self.base_url + self._session_token
    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/blaulichtsms/sensor.py", line 62, in async_setup_entry
    setup_result = await setup_blaulichtsms(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/sensor.py", line 87, in setup_blaulichtsms
    coordinator = await BlaulichtSMSCoordinator.get_coordinator(hass, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/coordinator.py", line 97, in get_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: can only concatenate str (not "NoneType") to str


*** Unexpected error fetching BlaulichtSMS data ***

Logger: custom_components.blaulichtsms.coordinator
Quelle: helpers/update_coordinator.py:315
Integration: Blaulicht SMS (Dokumentation)
Erstmals aufgetreten: 09:22:21 (2 Vorkommnisse)
Zuletzt protokolliert: 09:22:21

Unexpected error fetching BlaulichtSMS data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/coordinator.py", line 69, in _async_update_data
    return await self.api.get_last_alarm()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 97, in get_last_alarm
    alarms = await self.get_alarms()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 78, in get_alarms
    self.base_url + self._session_token
    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/coordinator.py", line 69, in _async_update_data
    return await self.api.get_last_alarm()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 97, in get_last_alarm
    alarms = await self.get_alarms()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/blaulichtsms.py", line 78, in get_alarms
    self.base_url + self._session_token
    ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/blaulichtsms/binary_sensor.py", line 68, in async_setup_entry
    setup_result = await setup_blaulichtsms(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/binary_sensor.py", line 93, in setup_blaulichtsms
    coordinator = await BlaulichtSMSCoordinator.get_coordinator(hass, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blaulichtsms/coordinator.py", line 97, in get_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: can only concatenate str (not "NoneType") to str
```

**Comment by r00tat** [comment]
Hi, ich habe lokal eine Neuinstallation durchgeführt und habe es neu einrichten können. 

Die Fehlermeldung hab ich zurück verfolgt. Steht in den logs auch noch `Failed to initialize blaulichtSMS session`?
Das würde bedeuten, dass die Zugangsdaten nicht korrekt sind.

Ich habe mit dem PR #40 jetzt beim Setup einen Check hinzugefügt. 

Kannst du es mit dem [Release 0.3.2](https://github.com/r00tat/hassio_blaulichtsms/releases/tag/0.3.2) nochmals versuchen?

**Comment by r-ober-t** [comment]
Hi,

es war tatsächlich ein Login-Problem 🥴. Ich hatte meine Blaulicht SMS-Login-Daten aus dem Kundenbereich verwendet und nicht die für den Einsatzmonitor. Ich habe nun einen weiteren Einsatzmonitor in der Verwaltung angelegt, und mit diesen Daten funktioniert es einwandfrei. Der Setup-Check hat mir dabei geholfen, den Fehler zu finden.

Vielen Dank.

**Comment by r-ober-t** [comment]
Hi,

es war tatsächlich ein Login-Problem 🥴. Ich hatte meine Blaulicht SMS-Login-Daten aus dem Kundenbereich verwendet und nicht die für den Einsatzmonitor. Ich habe nun einen weiteren Einsatzmonitor in der Verwaltung angelegt, und mit diesen Daten funktioniert es einwandfrei. Der Setup-Check hat mir dabei geholfen, den Fehler zu finden.

Vielen Dank.

**Comment by r00tat** [comment]
Freut mich, Berichte gerne von deinen Erfahrungen 

Hier ein Beispiel meiner Automatisierung:

```yaml
alias: Feuerwehr Einsatz
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.blaulichtsms_alarm_active
    from: "off"
    to: "on"
    enabled: true
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
    enabled: true
  - wait_template: "{{states('sensor.blaulichtsms_track_recipient') == 'yes'}}"
    continue_on_timeout: false
    timeout: "00:02:00"
  - if:
      - condition: state
        entity_id: sensor.blaulichtsms_track_recipient
        state: "yes"
      - condition: state
        entity_id: binary_sensor.blaulichtsms_alarm_active
        state: "on"
    then:
      - service: notify.mobile_app_pixel_6
        data:
          message: "{{ states('sensor.blaulichtsms_alarmtext') }}"
          title: Feuerwehr Einsatz
          data:
            actions:
              - action: URI
                title: Alarm öffnen
                uri: /lovelace/feuerwehr
        enabled: true
      - service: notify.mobile_app_pauls_pixel
        data:
          message: "{{ states('sensor.blaulichtsms_alarmtext') }}"
          title: Feuerwehr Einsatz
          data:
            actions:
              - action: URI
                title: Alarm öffnen
                uri: /lovelace/feuerwehr
        enabled: true
mode: single
```
